### PR TITLE
Fix mocha error: Error: global leak detected: disposable_email_providers

### PR DESCRIPTION
**Pull request by runk**

### CODE REVIEW

**Comment by runk** [comment]
Hey @sureshdsk do you think you can merge this tiny thing? Thanks.

**Comment by sureshdsk** [comment]
@runk  merged

**Comment by runk** [comment]
@sureshdsk awesome, thanks a lot! Can you please publish a new release to npm if you can?

**Comment by runk** [comment]
@sureshdsk would appreciate if you'd release it.

**Pull request merged**
